version: '3'

services:
   mysql:
     image: mysql:5.7
     volumes:
       - airflow_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: airflowpassword1dn2008
       MYSQL_DATABASE: airflow
       MYSQL_USER: airflow
       MYSQL_PASSWORD: airflow1dn2008

   airflow:
     depends_on:
       - mysql
     image: yogihardi/docker-airflow
     volumes:
       - airflow_dags:/usr/local/airflow/dags
       - airflow_logs:/usr/local/airflow/logs
     ports:
       - "8080:8080"
     restart: always
    
volumes:
    airflow_db_data:
    airflow_dags:
    airflow_logs:
